[build.environment]
HUGO_VERSION = "0.126.0"
DART_SASS_VERSION = "1.77.1"
TZ = "America/Caracas"

[build]
image = "ubuntu-24.04"
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify \
  """

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/**/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/**/*.{png,jpg,jpeg,gif,svg,webp,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/**/*.{woff,woff2,ttf,otf}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

